"""
Django settings for crm_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
from dotenv import load_dotenv
import dj_database_url

# Force-load .env from BASE_DIR and override existing env vars
# Prefer python-dotenv with utf-8-sig. If decoding fails, do a minimal manual loader.
ENV_PATH = BASE_DIR / '.env'
env_loaded = False
try:
    env_loaded = load_dotenv(dotenv_path=ENV_PATH, override=True, encoding='utf-8-sig')
except UnicodeDecodeError:
    try:
        # Manual load with utf-8-sig to strip BOM safely
        if ENV_PATH.exists():
            with open(ENV_PATH, 'r', encoding='utf-8-sig', errors='ignore') as f:
                for raw_line in f:
                    line = raw_line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        key, val = line.split('=', 1)
                        key = key.strip()
                        val = val.strip().strip('"').strip("'")
                        if key:
                            os.environ[key] = val
            env_loaded = True
    except Exception:
        env_loaded = False
except Exception:
    # As a last resort, try utf-16 (some editors save with UTF-16 LE BOM)
    try:
        env_loaded = load_dotenv(dotenv_path=ENV_PATH, override=True, encoding='utf-16')
    except Exception:
        env_loaded = False

# --- Begin compatibility shim for Django migrations ---
# Some Windows setups report that django.db.migrations lacks RunPython due to
# environment/path inconsistencies. Ensure the attribute is present early.
try:
    from django.db import migrations as _dj_migrations  # type: ignore
    if not hasattr(_dj_migrations, 'RunPython'):
        from django.db.migrations.operations import RunPython as _RunPython  # type: ignore
        _dj_migrations.RunPython = _RunPython  # type: ignore[attr-defined]
except Exception:
    # If Django isn't importable yet, ignore; app loading will import it later.
    pass
# --- End compatibility shim ---

def env_bool(var_name: str, default: str | bool = 'False') -> bool:
    val = os.getenv(var_name, str(default))
    return str(val).strip().lower() in ('1', 'true', 'yes', 'on')

# (Debug prints removed; using .env silently.)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key-here-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', 'True')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,aaa-crm-system.onrender.com,.onrender.com').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_filters',

    'crm_app',
    'accounts_app',
    'customers_app',
    'leads_app.apps.LeadsAppConfig',
    'deals_app',
    'activities_app.apps.ActivitiesAppConfig',
    'outbound_app.apps.OutboundAppConfig',
    'products',
    'notifications_app.apps.NotificationsAppConfig',
    'media_app',
    'invoices_app.apps.InvoicesAppConfig',
]

# Enable S3 media storage in production when USE_S3_MEDIA=true
# TEMPORARILY FORCED TO FALSE FOR DEBUGGING - 503 error after enquiry save
USE_S3 = env_bool('USE_S3', 'True')  # Re-enable S3 for media storage
if USE_S3:
    INSTALLED_APPS += ['storages']

# Custom S3 storage for Supabase to handle HeadObject 403 errors
from .storage_backends import SupabaseS3Storage

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts_app.middleware.RoleSuperuserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'crm_project.context_processors.followup_notifications',
                'crm_project.context_processors.user_role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use SQLite by default for local development, even if DATABASE_URL exists.
# To force using a remote Postgres URL, set USE_REMOTE_DB=True in .env
USE_REMOTE_DB = env_bool('USE_REMOTE_DB', 'False')
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL and USE_REMOTE_DB:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '600')),
            ssl_require=env_bool('DB_SSL_REQUIRED', 'False'),
        )
    }
    # Disable server-side cursors to prevent InvalidCursorName errors with poolers (e.g., PgBouncer)
    # and enable connection health checks to avoid using dead connections.
    # See: https://docs.djangoproject.com/en/4.2/ref/databases/#server-side-cursors
    #      https://docs.djangoproject.com/en/4.2/ref/settings/#databases/#conn-health-checks
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# (Debug prints removed.)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Use a valid timezone from the tz database
# See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TIME_ZONE = 'Asia/Kolkata'  # Changed from 'UTC' to 'Asia/Kolkata' (Indian Standard Time)

USE_I18N = True

# Keep this as True to use timezone-aware datetimes
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (uploads)
if USE_S3:
    # S3 Configuration with fallback defaults
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'auto')
    AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION', 's3v4')

    # Supabase S3-compatible API endpoint for uploads (must include /storage/v1/s3)
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'https://kvdtygryolbyjvtqphzj.storage.supabase.co/storage/v1/s3')
    AWS_S3_USE_SSL = True
    AWS_S3_VERIFY = True
    AWS_S3_ADDRESSING_STYLE = 'path'

    # Validate required S3 credentials
    s3_required_vars = ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_STORAGE_BUCKET_NAME']
    missing_vars = [var for var in s3_required_vars if not os.getenv(var)]

    if missing_vars:
        print(f"WARNING: Missing S3 environment variables: {', '.join(missing_vars)}")
        print("Falling back to local media storage")
        # Fallback to local storage if S3 credentials are missing
        MEDIA_URL = '/media/'
        MEDIA_ROOT = BASE_DIR / 'media'
        DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    else:
        # For Supabase Storage, use custom storage class to handle 403 HeadObject
        DEFAULT_FILE_STORAGE = 'crm_project.storage_backends.SupabaseS3Storage'
        _public_base = os.getenv(
            'AWS_S3_PUBLIC_BASE',
            f"https://kvdtygryolbyjvtqphzj.storage.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"
        ).rstrip('/')

        # For Supabase, we need the full public URL (with path) for URL generation
        # but just the domain for boto3 uploads
        custom_domain_from_env = os.getenv('AWS_S3_CUSTOM_DOMAIN')
        if custom_domain_from_env:
            # Keep the full URL for custom domain (includes path for serving)
            if custom_domain_from_env.startswith('http'):
                AWS_S3_CUSTOM_DOMAIN = custom_domain_from_env.replace('https://', '').replace('http://', '')
            else:
                AWS_S3_CUSTOM_DOMAIN = custom_domain_from_env
        else:
            # Use the full public base URL
            AWS_S3_CUSTOM_DOMAIN = _public_base.replace('https://', '').replace('http://', '')

        # Ensure https protocol is used for custom domain URLs
        AWS_S3_URL_PROTOCOL = 'https:'

        # Ensure the MEDIA_URL matches the public base without corrupting the scheme
        MEDIA_URL = _public_base.rstrip('/') + '/'

        # Sensible defaults
        AWS_S3_OBJECT_PARAMETERS = {
            'CacheControl': 'max-age=31536000, public',
        }
        AWS_QUERYSTRING_AUTH = False
        # Avoid legacy ACL warnings; bucket-level policy should grant public read
        AWS_DEFAULT_ACL = None
        # Avoid overwriting files with same name
        AWS_S3_FILE_OVERWRITE = False
        MEDIA_ROOT = ''  # Not used with S3

        # For Supabase Storage, disable exists() checks that cause HeadObject 403
        AWS_S3_MAX_MEMORY_SIZE = 0  # Disable multipart uploads for small files
        AWS_S3_USE_THREADS = False  # Disable threading

        # Safe debug prints (no secrets)
        try:
            print('[S3 CONFIG] bucket=', AWS_STORAGE_BUCKET_NAME,
                  ' endpoint=', AWS_S3_ENDPOINT_URL,
                  ' region=', AWS_S3_REGION_NAME,
                  ' addressing=', AWS_S3_ADDRESSING_STYLE,
                  ' media_url=', MEDIA_URL)
        except Exception:
            pass
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000', 
    'http://localhost:8000',
    # Allow IDE/browser preview ports during local development
    'http://127.0.0.1:57726',
    'http://localhost:57726',
    'https://*.onrender.com',
    'https://aaa-crm-system.onrender.com',
]

# Security Settings for Production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'

# Email Configuration
# https://docs.djangoproject.com/en/4.2/ref/settings/#email

# Default email backend (console for development, SMTP for production)
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration (configure these in Render environment variables)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', 'True')
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', 'False')

# Email credentials (set these in Render environment variables)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Default from email
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@yourapp.com')

# Admin email (for error notifications)
ADMINS = [
    ('Admin', os.getenv('ADMIN_EMAIL', 'admin@yourapp.com')),
]

# Server email (for automated messages)
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'crm_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'notifications_app': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
