# Generated by Django 4.2.7 on 2025-10-02 06:09

from django.db import migrations, models
from django.db.migrations.operations import RunPython

def convert_empty_strings_to_null(apps, schema_editor):
    """
    Convert empty strings in phone number fields to NULL.
    """
    Account = apps.get_model('accounts_app', 'Account')
    UserProfile = apps.get_model('accounts_app', 'UserProfile')
    
    Account.objects.filter(phone_number='').update(phone_number=None)
    UserProfile.objects.filter(phone='').update(phone=None)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_userrole_userprofile_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(convert_empty_strings_to_null, reverse_code=RunPython.noop),
    ]
