# Generated by Django 4.2.7 on 2025-10-02 06:34
# SAFE REPLACEMENT: Backend-aware primary key handling

from django.db import migrations, models
from django.db.migrations.operations import RunPython


def forwards_func(apps, schema_editor):
    """Backend-aware migration to handle primary key changes safely"""
    vendor = schema_editor.connection.vendor
    
    if vendor == 'sqlite':
        # SQLite: Use Django ORM operations (safer)
        Account = apps.get_model('accounts_app', 'Account')
        UserProfile = apps.get_model('accounts_app', 'UserProfile')
        
        # For SQLite, we'll keep the id fields and just ensure phone fields are unique
        # The actual PK change will be handled by migrations 0007 and 0008
        pass
    
    elif vendor == 'postgresql':
        # PostgreSQL: Skip this migration entirely
        # Let migrations 0007 and 0008 handle the proper PK setup
        pass


def backwards_func(apps, schema_editor):
    """Backwards migration - intentionally no-op to avoid issues"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_clean_phone_data'),
    ]

    operations = [
        RunPython(forwards_func, backwards_func),
    ]
