# Generated by Django 4.2.7 on 2025-10-02 05:29

from django.db import migrations, models
from django.db.models import Count


def deduplicate_and_clean_phones(apps, schema_editor):
    Lead = apps.get_model('leads_app', 'Lead')
    # 1) Convert empty strings to NULL
    Lead.objects.filter(phone_number='').update(phone_number=None)

    # 2) Find exact duplicates and null out all but the earliest one
    dup_values = (
        Lead.objects
        .exclude(phone_number__isnull=True)
        .values('phone_number')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for item in dup_values:
        value = item['phone_number']
        qs = Lead.objects.filter(phone_number=value).order_by('created_date', 'id')
        keep = qs.first()
        qs.exclude(pk=keep.pk).update(phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0001_initial'),
    ]

    operations = [
        # 0) Make the column nullable so we can set duplicates to NULL
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        # 1) Clean data BEFORE adding unique constraint
        migrations.RunPython(deduplicate_and_clean_phones, reverse_code=migrations.RunPython.noop),
        # 2) Enforce uniqueness (keeping null=True to allow missing numbers)
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
