# Generated by Django 4.2.7 on 2025-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0002_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
