# Generated by Django 4.2.7 on 2025-10-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0005_remove_lead_id_alter_lead_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contact',
        ),
    ]
