# Generated by Django 4.2.7 on 2025-10-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0005_contact_company'),
        ('leads_app', '0006_remove_lead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='customers_app.contact'),
        ),
    ]
