# Generated by Django for adding quantity and price fields to LeadProduct model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0007_lead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of the product'),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=10),
        ),
    ]
