# Generated by Django 4.2.7 on 2025-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0008_add_leadproduct_quantity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True),
        ),
    ]
