# Generated by Django 4.2.7 on 2025-10-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0011_drop_price_rate_from_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Prevents stage changes after fulfillment'),
        ),
    ]
