# Generated by Django 4.2.7 on 2025-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0012_add_is_locked_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
