# Generated by Django 4.2.7 on 2025-10-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0013_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_pending_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
