# Generated by Django 4.2.7 on 2025-10-11 06:33

from django.db import migrations


def migrate_won_to_invoice_sent(apps, schema_editor):
    """
    Migrate any enquiries with 'won' stage to 'invoice_sent' stage.
    """
    Lead = apps.get_model('leads_app', 'Lead')
    # Update all leads with 'won' stage to 'invoice_sent'
    Lead.objects.filter(enquiry_stage='won').update(enquiry_stage='invoice_sent')


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0014_lead_is_pending_review_alter_lead_phone_number'),
    ]

    operations = [
        migrations.RunPython(migrate_won_to_invoice_sent, reverse_code=migrations.RunPython.noop),
    ]
