# Generated by Django 4.2.7 on 2025-10-11 06:38

from django.db import migrations


def migrate_invoice_made_to_invoice_sent(apps, schema_editor):
    """
    Migrate any enquiries with 'invoice_made' stage to 'invoice_sent' stage.
    """
    Lead = apps.get_model('leads_app', 'Lead')
    # Update all leads with 'invoice_made' stage to 'invoice_sent'
    Lead.objects.filter(enquiry_stage='invoice_made').update(enquiry_stage='invoice_sent')


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0015_migrate_won_to_invoice_sent'),
    ]

    operations = [
        migrations.RunPython(migrate_invoice_made_to_invoice_sent, reverse_code=migrations.RunPython.noop),
    ]
