# Generated by Django 4.2.7 on 2025-10-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0016_migrate_invoice_made_to_invoice_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadproduct',
            name='description',
        ),
        migrations.AlterField(
            model_name='lead',
            name='enquiry_stage',
            field=models.CharField(choices=[('enquiry_received', 'Enquiry Received'), ('quotation_sent', 'Quotation Sent'), ('negotiation', 'Negotiation'), ('proforma_invoice_sent', 'Proforma Invoice Sent (PI Sent)'), ('invoice_sent', 'Invoice Sent'), ('lost', 'Lost')], default='enquiry_received', max_length=30),
        ),
    ]
