# Generated by Django 4.2.7 on 2025-10-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0017_remove_description_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image_url',
            field=models.URLField(blank=True, help_text='Google Drive image URL for the enquiry', null=True),
        ),
    ]
