# Generated by Django 4.2.7 on 2025-12-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0019_lead_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproduct',
            name='ankle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='people',
            field=models.CharField(blank=True, help_text='Capacity / number of people for first aid kits or similar items', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
