# Generated by Django 4.2.7 on 2025-09-23 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers_app', '0001_initial'),
        ('leads_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Use {customer_name}, {company_name} for personalization')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('PHONE', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('MEETING', 'In-Person Meeting'), ('VIDEO_CALL', 'Video Call'), ('LINKEDIN', 'LinkedIn Message'), ('OTHER', 'Other')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('POSITIVE', 'Positive Response'), ('NEUTRAL', 'Neutral Response'), ('NEGATIVE', 'Negative Response'), ('NO_RESPONSE', 'No Response'), ('CALLBACK_REQUESTED', 'Callback Requested'), ('NOT_INTERESTED', 'Not Interested'), ('INTERESTED', 'Showed Interest'), ('MEETING_SCHEDULED', 'Meeting Scheduled')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the conversation', max_length=2000)),
                ('detailed_notes', models.TextField(blank=True, help_text='Detailed notes and observations')),
                ('next_step', models.CharField(choices=[('NONE', 'None'), ('FOLLOW_UP', 'Schedule Follow-up'), ('SEND_CATALOGUE', 'Send Product Catalogue'), ('SEND_QUOTE', 'Send Quotation'), ('SEND_PROPOSAL', 'Send Proposal'), ('SCHEDULE_DEMO', 'Schedule Product Demo'), ('SCHEDULE_MEETING', 'Schedule Meeting'), ('CREATE_ENQUIRY', 'Create Enquiry'), ('CONVERT_LEAD', 'Convert to Lead'), ('CLOSE_WON', 'Mark as Won'), ('CLOSE_LOST', 'Mark as Lost')], default='NONE', max_length=30)),
                ('next_step_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_reminder', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Call/meeting duration in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_activities', to='outbound_app.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_activities', to='customers_app.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_from', to='leads_app.lead')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='outbound_app.messagetemplate')),
            ],
            options={
                'verbose_name': 'Outbound Activity',
                'verbose_name_plural': 'Outbound Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', 'created_at'], name='outbound_ap_contact_38193a_idx')],
            },
        ),
    ]
