# Generated by Django 4.2.7 on 2025-10-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0001_initial'),
        ('outbound_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundactivity',
            name='contact',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='outbound_activities',
                to='customers_app.contact',
            ),
        ),
    ]
