# Generated by Django 4.2.7 on 2025-10-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0006_merge_20251007_1827'),
        ('outbound_app', '0002_auto_20251002_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundactivity',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_activities', to='customers_app.contact', to_field='phone_number'),
        ),
    ]
