# Generated by Django 4.2.7 on 2025-10-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0003_remove_contact_id_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
    ]
