# Generated by Django 4.2.7 on 2025-10-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_remove_account_id_remove_userprofile_id_and_more'),
        ('customers_app', '0004_remove_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='accounts_app.account'),
        ),
    ]
