# Generated by Django 4.2.7 on 2025-10-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_app', '0002_alter_contact_options_and_more'),
        ('customers_app', '0005_contact_company'),
    ]

    operations = [
    ]
