# Generated by Django 4.2.7 on 2025-10-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_fix_userprofile_phone_primary_key_postgres'),
        ('customers_app', '0006_merge_20251007_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='accounts_app.account', to_field='phone_number'),
        ),
    ]
